# Generated by Django 4.1.5 on 2023-01-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ID Number'),
        ),
    ]
